trigger:
- main

stages:
  - stage: 
    displayName: Build
    jobs:
      - job: JobA
        pool: 
          vmImage: window-latest
        steps:
         - task: CmdLine@2
           inputs:
             script: 'echo Hello from Job A'
             
         - script: echo 'Hello from Job A'