trigger:
- main

stages:
  - stage: 
    displayName: Build
    jobs:
      - job: "BuildProject"
        variables: 
          BuildConfiguration: Release
        pool:
          # vmImage: ubuntu-latest
          name: dentsu-pool
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build Task
            inputs:
              command: 'build'
          
          - task: DotNetCoreCLI@2
            displayName: Publish To Artifact Staging Directory
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'artifact'
              publishLocation: 'Container'