trigger:
- main

stages:
  - stage: 
    displayName: Build
    jobs:
      - job: "Build_.Net_Project"
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'